### ISSUE TITLE
Experiment with EDGI <=> Archivers Slack bridge

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/overview#154] opened 2017-06-15 06:53 UTC
Reticked from #46 

This is the free tool we can host on Heroku: https://github.com/civictechto/slackbridge

These are the evolving notes and plan: https://hackmd.io/CYTgHATArAjARmAtAFmMgDC6BmRIBsMApngMaFREggDs+AhmEA==?view

Slack context: https://edgi.slack.com/archives/G5R52CRD3/p1497403127198175?thread_ts=1497362861.018496&cid=G5R52CRD3

cc: @murphyofglad

**Comment by patcon** [comment] 2017-06-15 06:59
caveat: (re: @b5's question in last thread)

setup is a little tedious -- each bidirectional bridge (they can be one direction) requires the following tedious envvar config:
https://github.com/CivicTechTO/slackbridge/blob/heroku-deploy/sample.env#L4-L15

but once it's set up, it's pretty nice. it's a bit more intuitive when people have the same usernames on each slack, so we might want to coach folks on that.

also, perk is that when you're in one end of a "portal", you can leave the connected channel on the other end. This in practice means less mental spaces where it's ambiguous which channel (on which slack team) is best, because they are essentially the same.

main caveat is that portal from EDGI to Archivers break a social contract that folks might have about EDGI channels -- that only vetted people are reading. Should be very careful to pin a disclaimer, or perhaps some specific phrase/emoji in channel topic to warn

**Comment by titaniumbones** [comment] 2017-06-15 11:08
So this seems like a great idea to me.  


> also, perk is that when you're in one end of a "portal", you can leave the connected channel on the other end. This in practice means less mental spaces where it's ambiguous which channel (on which slack team) is best, because they are essentially the same.

that's exactly the kind of slight friction that I would be so very glad to see diminish.


> main caveat is that portal from EDGI to Archivers break a social contract that folks might have about EDGI channels -- that only vetted people are reading. Should be very careful to pin a disclaimer, or perhaps some specific phrase/emoji in channel topic to warn

I wonder if we can choose, as a test, a channel in EDGI that already has a very open feel. Web monitoring in some ways feels like the obvious choice, but I haven't noticed if maybe the web monitoring analyst team sometimes shares semi-private stuff there.  

archiving_techne is the other obvious choice.

**Comment by patcon** [comment] 2017-06-15 15:50
> a channel in EDGI that already has a very open feel.

good thought!

cc: webmon reps @trinberg @ambergman @mayaad @Mr0grog @lightandluck @danielballan

**Comment by patcon** [comment] 2017-06-15 15:54
just to clarify for those @-mentioned above: it's arbitrary whether we create a new channel for "sharing" or just stitch the existing ones on each team together where sensible. I prefer the ~former~ (oops!) latter (ie. less fragmentation, not more) but whichever.

I could imagine connecting _existing_ channels across slack teams (ie. no special new one), and if ppl ever feel a tension of not being able to speak freely, then they could _then_ create a new non-shared one to resolve that tension. (the tech term for this approach is _avoiding "premature optimization"_, which is often seen as the root of much complexity :) )

**Comment by Mr0grog** [comment] 2017-06-15 17:33
I think @titaniumbones is right on with experimenting on one or two channels; we should not force any EDGI members who feel uncomfortable with this into it.

While I both #archiving-techne and #web-monitoring (not #web-monitoring-team) seem like good candidates to me. In the #web-monitoring case, we should definitely make sure people there are cool with it. The conversation on the EDGI one is pretty non-technical, non-product focused, while the one on Archivers is the opposite (I think both sides could do with hearing more of each others’ work and process, which would really be aided by merging them, but the flavor of the two channels is _currently_ quite different).

**Comment by Mr0grog** [comment] 2017-06-15 17:34
(As a side note, this is **SUPER COOL,** thank you for finding it, @patcon!)

**Comment by dcwalk** [comment] 2017-06-16 10:04
I agree with Rob's points, RE: web monitoring and taking care in moving forward. 

`#archiving_techne` was the channel originally proposed waaaay back when we were attempting this before. I'd like to vote for that as a first pass as we already have a sensitive channel, there are some links that maybe wouldn't get dropped immediately, but my hope is it wouldn't impact it too much. I think this could be discussed and voted on (with appropriate notifications) at the first Archiving/Tech WG meeting?

**Comment by Mr0grog** [comment] 2017-06-20 16:44
@patcon where are we on this for `#archiving_techne`?

Should I post to `Archivers#dev-webmonitoring` and `EDGI#web_monitoring` about this? (Will also bring up at Analyst meeting tomorrow for vote/decision on the EDGI slack side.)

**Comment by patcon** [comment] 2017-06-22 19:40
Started making notes/plan here a few days ago: https://hackmd.io/CYTgHATArAjARmAtAFmMgDC6BmRIBsMApngMaFREggDs+AhmEA==

Totally agree not to force.

Key thing I realised while writing that doc is that **the goal is prob not to "merge and minimize channels", but to (when possible), ensure same  @mental/social space exists regardless of which slack we're in**. So that might involve actually _creating_ a non-technical channel on Archivers Slack, and then wiring it up to `edgi#web_monitoring` (if that's something the team wants). It's the ambiguity of Slacks, not the ambiguity of channels, that strikes me as the highest mental burden (but feel free to push back on that characterization), and most confusing for new contributors :)

**Comment by patcon** [comment] 2017-06-22 19:55
@dcwalk re: `edgi#archiving_techne`

1. Should we indicate the connectedness via a suffix, like `-portal`?
4. Given the channel inventory linked above, what feels right to connect to `edgi#archiving_techne`?
2. Should we try to make channel name consistent across both (less cog load)?
3. Should we consider renaming `edgi#archiving_techne` while we're at this? (I;ve realized I have no idea what it means -- very confusing with the "tech" bit.)

@Mr0grog curious to hear your thoughts on how you might imagine wiring up webmon rooms:
1. **Do we ensure two channels/spaces in both slacks?** "Non-technical" and "technical"? Or perhaps better framed as "general" and "technical/dev"?
1. **Do we force them to merge into one space?** We could always start with less -- ie. a single merged room, but make it known that if folks feel a tension or confusion, we will poof a new connected portal channel and separate them again. 

(1) strikes me as less imposition of change in mental models :)

**Comment by Mr0grog** [comment] 2017-06-22 20:39
>  ensure same space exists regardless of which slack we're in. So that might involve actually creating a non-technical channel on Archivers Slack, and then wiring it up to `EDGI#web_monitoring`

We actually talked through this on the call yesterday; `Archivers#dev-webmonitoring` is not really super technical and already serves as the space for technical and non-technical discussion about web monitoring on Archivers… plus, we still have `#dev-webmonitoring-ui`. _So we probably don’t want a separate/new channel for this._

If it works out poorly, it takes approximately 30 seconds of work to create a new Slack channel to partition off technical talk.

**Comment by titaniumbones** [comment] 2017-06-22 20:42
@patcon the discussion yest (6/21, not sure if video is up yet) at the web-monitoring meeting was helpful on this:
- General feeling was that `#web-monitoring` and `#dev-webmonitoring` were a good match
- @suchthis made an excellent and very helpful point: that we dont want to overgeneralize channels, but instead ensure that everyone is subscribed to precisely those channels that matter most to them, and reduce confusion of overlaps.  This accords very well w/ yr point above. 

So: merging precisely the existing channels seems like a good first step. If you are confident that you can easily accomplish this, then pinning a wrning to those channels letting people know that we're doing so, would be a great first step. I am happy to do that as soon as you think you are close to having this set up.

**Comment by patcon** [comment] 2017-06-22 22:25
Perf. Will do this next. Thanks both.

**Comment by dcwalk** [comment] 2017-06-24 21:22
Hey, I'm still game to have the `#archival_techne` bridged, but I'm actually having a hard time finding a 100% match.

RE: Techne, my read is it is akin to 'craft' but I think when it is used now it speaks to a stance and set of intellectual/critical commitments around broadening/reflecting on the skills and knowledge pulled in.. sorta..?

Sooo.... my backup suggesting is `#community_building`, as they have the same name and serve the same purpose. I think also are within the Archiving WG remit to suggest/guide as they both came out of archiving event stuff.

**Comment by patcon** [comment] 2017-06-30 15:27
- [x] Created heroku app: `edgi-slackbridge`
- [x] Added to [Service and Deployment](https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2) doc
- [x] Added `enviroDGI@gmail.com` as app collaborator (anyone else want perms?)
- [ ] create heroku team for owning apps (Related critical issue imho: https://github.com/edgi-govdata-archiving/overview/issues/160)
- [x] created portal: `edgi#web_monitoring <=> archivers#dev-webmonitoring`
- [x] create portal: `edgi#community_buidling <=> archivers#community-building`

## Open Questions

1. Do we **sync names of channels on both sides** to reduce space for lack of clarity (and to emphasize that there are both the same place)?
2. Should we **add a channel suffix to hint** at which channels are portals (again, would help point out where we're breaking assumed EDGI social contract of who the audience might be)?

**Comment by trinberg** [comment] 2017-06-30 16:00
Quick note: you probably know this, but you currently can't edit or delete the message that was posted in the parallel channel. Any chance that could be fixed? Could lead to some embarrassing moments :) 

Also note that in-thread commenting doesn't work on the parallel channel. It would be great to keep encouraging folks to discuss in thread!

@patcon

**Comment by titaniumbones** [comment] 2017-06-30 16:29
Hmm, one partial solution would be to recommend leaving the parallel channel? 

I don't think slack recognizes the 2 88thusers as the same entity, so the issue is unlikely to be fixable by some setting on the bridge. 

On June 30, 2017 12:00:05 PM EDT, trinberg <notifications@github.com> wrote:
>Quick note: you probably know this, but you currently can't edit or
>delete the message that was posted in the parallel channel. Any chance
>that could be fixed? Could lead to some embarrassing moments :) @patcon
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/overview/issues/154#issuecomment-312306500

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by patcon** [comment] 2017-06-30 16:34
caveats so far:
1. reaction emoji don't go through portal (might be simple and really useful to address)
2. threaded messages get "unthreaded" (prob pretty hard to address)
3. can't see `user is typing` notification (doesn't seem worth resolving?)
4. can't edit messages (h/t @trinberg ). agree with @titaniumbones, i can't imagine this being easily solvable. the messages are technically by a bot, and the bridge is really simple, so it doesn't know who's who... :(
    1. corollary: edits only seen on one side. original message seen on other side.

**Comment by patcon** [comment] 2017-06-30 16:36
Fuzzy fix for (1), (2), (3) is to encourage ppl to favour one side of bridge for now. I lean toward Archivers side, as that's where most people can get access (given relative ease of sign-up)

**Comment by patcon** [comment] 2017-06-30 16:38
Other fuzzy fix: recommend that people be wary of important edits in "portal" channels.

We should make a pinned message for things like this.

**Comment by patcon** [comment] 2017-06-30 16:50
Currently investigating whether https://slackline.io resolves any of this.

Connected their "help" channel as [`archivers#slackline-chat`](https://archivers.slack.com/messages/C62EFS30D/), and asking there.

Also, their FAQ says that they sometimes work with non-profits. Their pricing is $30/month for 5 "portals".

http://sameroom.io/ is a similar service fwiw, but not just slack. (and $50/month)

**Comment by patcon** [comment] 2017-07-07 22:31
Slackline has confirmed in `archivers#slackline-chat` that their service doesn't address any of our caveats, so then it's only perk is ease of setup (ie. non-technical)

**Comment by patcon** [comment] 2017-07-08 20:22
~~New realization: We might be limited in the number of channels we can bridge, due to limitations on how slackbridge works, and bc slack limits the integrations for free teams. I've opened a rlated ticket here: https://github.com/ossobv/slackbridge/issues/9~~

EDIT: no longer a concern. see https://github.com/edgi-govdata-archiving/overview/issues/154#issuecomment-315137248

**Comment by dcwalk** [comment] 2017-07-10 16:27
Oh shoot, this feels like it could be a big block :/

**Comment by patcon** [comment] 2017-07-12 19:28
As per @shapironick's suggestion [on Slack](https://edgi.slack.com/archives/C57QL8M1T/p1499821773562174), added `#data-together` bridge to the hackmd doc linked in original issue. Great idea!

**Comment by patcon** [comment] 2017-07-12 21:01
`#community-building` channels are now bridged

**Comment by patcon** [comment] 2017-07-13 06:46
ok, bridged `#datatogether` with edgi as well!

**Comment by patcon** [comment] 2017-07-13 16:52
And GREAT NEWS! Confirmed that an arbitrary number of "incoming webhooks" and "outgoing webhooks" still just count as **two** integrations! So this approach isn't limited!

**Comment by patcon** [comment] 2017-07-13 17:39
Created a little note to link as part of a pinned message in each bridged channel. It's general and not EDGI-specific.
https://hackmd.io/s/BJWOLQBrZ#

The pinned note text I've been using on the EDGI side:

```
For easier communication, this channel is set up as a "bridge" between two Slack teams.

It connects `edgi#datatogether` and `archivers#datatogether.`

All users of this channel should read these *important caveats* that will affect conversations here:
https://hackmd.io/s/BJWOLQBrZ#

Please be aware that *membership in Archivers Slack is open to all*, and not subject to memberizing procedures from the _EDGI Protocol_.
```

**Comment by dcwalk** [comment] 2017-07-17 18:17
@patcon I feel like we are close to moving out of "experimentation" phase on this, what are the remaining todos to get us there? I'm happy to pitch in, but not sure the status!

**Comment by dcwalk** [comment] 2017-07-18 15:57
@patcon, it looks like the bridge is one way for `#datatogether`:

EDGI --> Archivers working
Archivers --> EDGI is not (both my messages and @machawk1's not heading back)

**Comment by dcwalk** [comment] 2017-07-18 16:37
whoa -- plot thickens! The Data Together bridge is wire-crossed with `#dev-webmonitoring`

So, what I'm seeing is:
EDGI `#datatogether` --> Archivers `#datatogether`
Archivers `#dev-webmonitoring` --> EDGI `#datatogether`
EDGI `#web_monitoring` --> Archivers `#dev-webmonitoring`

**Comment by Mr0grog** [comment] 2017-07-18 16:40
Uhoh. I’ve been signed out of EDGI `#web_monitoring` but now that I’m checking I’m seeing the same. Wonder if this has been the source of some miscommunications.

**Comment by dcwalk** [comment] 2017-07-18 16:43
@Mr0grog -- I think this may have started when the Data Together bridge was set up, so 5 days ago? (per @patcon's comment above)

I am going into a meeting but can crash through this aft if @patcon doesn't get to it first 🙏 🙏

**Comment by dcwalk** [comment] 2017-07-19 15:46
Update:

I believe I have corrected the cross-channel messages, which were a result of a missing outgoing webhook on the Archivers side. In addition the `#dev-webmonitoring` webhook token was reused in the config var for that `PORTAL` causing some strange-ish loop with messages.

Just did a very basic test and it appears to be working...? Would welcome confirmation from @patcon when they get the chance :)

----

Now, back on to my comment above:
> I feel like we are close to moving out of "experimentation" phase on this, what are the remaining todos to get us there? I'm happy to pitch in, but not sure the status!

**Comment by dcwalk** [comment] 2017-07-31 18:08
Okay, I'm going to close this for now, we _are_ experimenting, and things that need to be resolved should be ticketed as necessary

**Closed as completed by dcwalk** 2017-07-31 18:08 UTC
Labels: coordination

**Comment by patcon** [comment] 2017-09-20 15:55
FYI, slack is now beta-testing an official feature called Shared Channels: https://slackhq.com/introducing-shared-channels-where-you-can-work-with-anyone-in-slack-8c5d2a943f57

The beta is only available to paid teams, but worth watching in case it's useful to us later.
